/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PT_PrintingMemberRole;

import userinterface.PT_ManageRole.*;
import Business.Enterprise.Enterprise;
import userinterface.PB_ManagerRole.*;
import Business.OrderSystem.OrderDirectory;
import Business.OrderSystem.OrderItem;
import Business.Organization.Organization;
import Business.Organization.PT_PrintingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Date;
import javax.swing.table.JTableHeader;
import static userinterface.MainJFrame.dB4OUtil;
import static userinterface.MainJFrame.log;
import static userinterface.MainJFrame.system;
import zOthers.changeDate;
/**
 *
 * @author admin
 */
public class PTMan_workAreaJpanel extends javax.swing.JPanel {

    private JPanel container;
    private UserAccount user;
   
    public PTMan_workAreaJpanel( JPanel container, UserAccount user) {
        initComponents();
        log.info("Login: Printer Man User:"+user.getUsername());
        this.container=container;
        this.user=user;
        this.setBackground(new Color(253,251,239));
       labelUser.setText("Enterprise: "+user.getEmployee().getEnterprise().getEnterpriseName()+"("+user.getEmployee().getEnterprise().getNetwork().getName()+")"); 
        JTableHeader head = tblQueue.getTableHeader(); // 创建表格标题对象
        head.setPreferredSize(new Dimension(head.getWidth(), 24));// 设置表头大小
        head.setFont(new Font("Times New Romans", Font.PLAIN, 24));// 设置表格字体
        JTableHeader head1 = tblOrderItem.getTableHeader(); // 创建表格标题对象
        head1.setPreferredSize(new Dimension(head1.getWidth(), 24));// 设置表头大小
        head1.setFont(new Font("Times New Romans", Font.PLAIN, 24));// 设置表格字体
        populate();
        
        
 
        
    }
    public void populateItems(WorkRequest wr){
        if(wr!=null){
            DefaultTableModel dtm=(DefaultTableModel)tblOrderItem.getModel();
            dtm.setRowCount(0);
            for(OrderItem oi:wr.getOrder().getOrderItems()){
                Object[] r=new Object[4];
                r[0]=oi;
                r[1]=oi.getQuantity()+"";
              
             if(wr.getSenderEnterprise()!=null){
                    r[2]=wr.getSenderEnterprise().getEnterpriseName();
                                  
                }else{
                    r[2]=wr.getSenderUserAccount().getUsername();
                    
                }           
                
                r[3]=wr.getOrder().getStatus();
                dtm.addRow(r);

            }
        }
        
    }
    public void populate(){
        
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:user.getWorkQueue().getWorkRequestList()){
            if(wr.getStatus().equals("Uncompleted")){
                Object[] row=new Object[6];
                row[0]=new changeDate().change(wr.getRequestDate());
                if(wr.getSenderEnterprise()!=null){
                    row[1]=wr.getSenderEnterprise().getEnterpriseName();
                             
                }else{
                    row[1]=wr.getSenderUserAccount().getUsername();
                 
                }           
                row[2]=wr.getStatus();
                row[3]=wr.getMessage();
                row[4]=wr;
                row[5]=wr.getResolveDate()==null?"":new changeDate().change(wr.getResolveDate());
                dtm.addRow(row);
            }            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDetails = new javax.swing.JButton();
        btnUnfinished = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        btnCommit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQueue = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderItem = new javax.swing.JTable();

        setBackground(new java.awt.Color(253, 251, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDetails.setFont(new java.awt.Font("Tekton Pro Ext", 1, 28)); // NOI18N
        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnUnfinished.setFont(new java.awt.Font("Tekton Pro Ext", 1, 28)); // NOI18N
        btnUnfinished.setText("Unfinished");
        btnUnfinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnfinishedActionPerformed(evt);
            }
        });
        add(btnUnfinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnAll.setFont(new java.awt.Font("Tekton Pro Ext", 1, 28)); // NOI18N
        btnAll.setText("Finished");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        btnCommit.setFont(new java.awt.Font("Tekton Pro Ext", 1, 28)); // NOI18N
        btnCommit.setText("Completed");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        add(btnCommit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 210, 40));

        jLabel10.setFont(new java.awt.Font("Tekton Pro Ext", 3, 36)); // NOI18N
        jLabel10.setText("Welcome! Printer Man !");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        labelUser.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUser.setText("labelUser");
        add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 350, 40));

        tblQueue.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestDate", "Sender", "WR Status", "Message", "Order ID", "ResolveDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQueue.setRowHeight(25);
        jScrollPane1.setViewportView(tblQueue);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 880, 370));

        tblOrderItem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "BookName", "Quantity", "Sender", "Order Status"
            }
        ));
        tblOrderItem.setRowHeight(25);
        jScrollPane2.setViewportView(tblOrderItem);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 880, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
                int row=tblQueue.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a work reuqest", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            WorkRequest wr=(WorkRequest)tblQueue.getValueAt(row, 4);
            populateItems(wr);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnUnfinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnfinishedActionPerformed
        btnCommit.setEnabled(true);
        populate();
    }//GEN-LAST:event_btnUnfinishedActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        btnCommit.setEnabled(false);
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:user.getWorkQueue().getWorkRequestList()){
               if(wr.getStatus().equals("Completed")){
            Object[] row=new Object[6];
                           row[0]=new changeDate().change(wr.getRequestDate());
                if(wr.getSenderEnterprise()!=null){
                    row[1]=wr.getSenderEnterprise().getEnterpriseName();
                             
                }else{
                    row[1]=wr.getSenderUserAccount().getUsername();
                 
                }           
                row[2]=wr.getStatus();
                row[3]=wr.getMessage();
                row[4]=wr;
                row[5]=wr.getResolveDate()==null?"":new changeDate().change(wr.getResolveDate());
            dtm.addRow(row);
               }
        }
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed

        
       int row=tblQueue.getSelectedRow();

        
        if(row<0){           
            JOptionPane.showMessageDialog(null, "Please select a work reuqest", "Warning", JOptionPane.WARNING_MESSAGE);       
            
        }else{
            WorkRequest wr=(WorkRequest)tblQueue.getValueAt(row, 4);
            
           

             //message
            
            int mesg = JOptionPane.showConfirmDialog(null, "Are you sure to process this request?", " WarningDialog!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(mesg==JOptionPane.YES_OPTION){
                
                JOptionPane.showMessageDialog(null, "A work request has been processed.");
                wr.setStatus("Completed");
                wr.setResolveDate(new Date());
                wr.getOrder().setStatus("Finished Print");
                DefaultTableModel dtm=(DefaultTableModel)tblOrderItem.getModel();
                dtm.setRowCount(0);
                populate(); 
                dB4OUtil.storeSystem(system); 
            }
                
        }
                    

    }//GEN-LAST:event_btnCommitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnUnfinished;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTable tblOrderItem;
    private javax.swing.JTable tblQueue;
    // End of variables declaration//GEN-END:variables
}
