/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PB_ManagerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PrinterEnterprise;
import Business.OrderSystem.OrderItem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import userinterface.Deli_ManRole.DeliMan_workAreaJpanel;
import userinterface.MainJFrame;
import static userinterface.MainJFrame.dB4OUtil;
import static userinterface.MainJFrame.system;
import zOthers.playMusic;

/**
 *
 * @author admin
 */
public class PB_newRequestJPanel extends javax.swing.JPanel {

    private JPanel container;
    private WorkRequest wr;
    private UserAccount ua;
    //EcoSystem system;
    public PB_newRequestJPanel(JPanel container,WorkRequest wr,UserAccount ua) {
        initComponents();
        this.container=container;
        this.wr=wr;
        this.ua=ua;
        this.setBackground(new Color(253,251,239));
       // JTableHeader head1 = tblOrderItem.getTableHeader(); // 创建表格标题对象
       //head1.setPreferredSize(new Dimension(head1.getWidth(), 24));// 设置表头大小
        //head1.setFont(new Font("Times New Roman", Font.PLAIN, 24));// 设置表格字体
        populate();
        for(Enterprise pe:ua.getEmployee().getEnterprise().getNetwork().getEnterpriseDirectory().getEnterpriseList()){
            if(pe.getEnterpriseType().equals("Type-Printer") && pe.getNetwork().getNetworkID()==ua.getEmployee().getEnterprise().getNetwork().getNetworkID()){ 
                if(pe.getOrganizationDirectory().getOrganizationList().size()!=0){
                for(Organization or:pe.getOrganizationDirectory().getOrganizationList()){
                    if(or.getOrgtypename().equals("PT_PrintingOrganization"))
                    comboPrint.addItem(pe.toString());
                
                }
                     
                }
               
            }
        }
    }
    
    public void populate(){
         for(OrderItem oi:wr.getOrder().getOrderItems()){
                Object[] r=new Object[5];
                t1.setText(oi.getBookname());
                t2.setText(oi.getQuantity()+"");
              
             if(wr.getSenderEnterprise()!=null){
                    t3.setText(wr.getSenderEnterprise().getEnterpriseName());
                    t4.setText(wr.getSenderEnterprise().getPhone());               
                }else{
                    t3.setText(wr.getSenderUserAccount().getUsername());
                    t4.setText(wr.getSenderUserAccount().getPhone());
                }           
                
                t5.setText(wr.getOrder().getStatus());
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboPrint = new javax.swing.JComboBox<>();
        btnCommit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(253, 251, 239));
        setPreferredSize(new java.awt.Dimension(950, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 3, 48)); // NOI18N
        jLabel1.setText("New Request To Printer!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        btnBack.setFont(new java.awt.Font("Tekton Pro Ext", 1, 30)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Choose a Printer:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, -1, -1));

        comboPrint.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        add(comboPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 220, -1));

        btnCommit.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        add(btnCommit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("BookName:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Sender:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 110, 50));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Order Status:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 210, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sender Phone:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 210, -1));

        t5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        t5.setEnabled(false);
        add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 390, -1));

        t1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        t1.setEnabled(false);
        add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 390, -1));

        t2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        t2.setEnabled(false);
        add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 390, -1));

        t3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        t3.setEnabled(false);
        add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 390, -1));

        t4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        t4.setEnabled(false);
        add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 390, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        Component[] coms=container.getComponents();
        Component c=(Component)coms[coms.length-1];
        PB_workAreaJPanel jp=(PB_workAreaJPanel)c;
        jp.populate();
        jp.populateItems(null);  
        jp.cleartable();
        CardLayout l=(CardLayout)container.getLayout();
        l.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        String printer=(String)comboPrint.getSelectedItem();
        Enterprise selectedPrint=null;
        for(Enterprise e:ua.getEmployee().getEnterprise().getNetwork().getEnterpriseDirectory().getEnterpriseList()){
            if(e.getEnterpriseName().equals(printer)){
                selectedPrint=e;
            }
        }
        if(selectedPrint!=null){
            for(Enterprise e:ua.getEmployee().getEnterprise().getNetwork().getEnterpriseDirectory().getEnterpriseList()){
                if(e.equals(selectedPrint)){
                    for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                        if(o.getOrgtypename().equals("PT_ManagementOrganization")){
                            WorkRequest newReq=new WorkRequest();
                            newReq.setOrder(wr.getOrder());
                            newReq.setSenderEnterprise(ua.getEmployee().getEnterprise());
                            newReq.setStatus("Uncompleted");
                            newReq.setReceiverEnterprise(e);
                            newReq.setRequestDate(new Date());
                            //message
                            int check=JOptionPane.YES_NO_OPTION;
                            String mesg = JOptionPane.showInputDialog(null,"Message: \n","Mesg",check);        
                            if(check==JOptionPane.YES_OPTION){
                                newReq.setMessage(mesg);
                                try {
                                    new playMusic().play("src/zOthers/ding.wav");
                                } catch (IOException ex) {
                                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                JOptionPane.showMessageDialog(null, "A new work request has been sent out successfully.");
                               wr.setStatus("Completed");
                               wr.setResolveDate(new Date());
                               wr.getOrder().setStatus("Waiting Printer Process");
                                comboPrint.setEnabled(false);
                                o.getWorkQueue().addNewRequest(newReq);
                                btnCommit.setEnabled(false);
                                dB4OUtil.storeSystem(system); 
                                populate();
                              
                            }
                           // o.getWorkQueue().addNewRequest(newReq);
                        }
                    }
                }           
            }            
        }
        
        
    }//GEN-LAST:event_btnCommitActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommit;
    private javax.swing.JComboBox<String> comboPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
