/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PB_ManagerRole;

import Business.OrderSystem.OrderItem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.math.BigDecimal;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class PB_RequestDetailsJPanel extends javax.swing.JPanel {

    JPanel container;
    WorkRequest wr;
    private UserAccount user;
    public PB_RequestDetailsJPanel(JPanel container,WorkRequest wr, UserAccount user) {
        initComponents();
        this.container=container;
        this.wr=wr;
        this.user=user;
        txtSender1.setText(wr.getSender().getUsername());
        txtRequestDate.setText(wr.getRequestDate().toString());
        txtResolvedDate.setText(wr.getResolveDate().toString());
        populate();
    }
    
    public void populate(){
        DefaultTableModel dtm=(DefaultTableModel)tblOrderItem.getModel();
        dtm.setRowCount(0);
        for(OrderItem oi:wr.getOrder().getOrderitems()){
            Object[] row=new Object[4];
            row[0]=oi;
            row[1]=oi.getQuantity()+"";
            row[2]=oi.getPrice()+"";
            BigDecimal quantity=new BigDecimal(Double.toString(oi.getQuantity()));
            BigDecimal price=new BigDecimal(Double.toString(oi.getPrice()));
            row[3]=price.multiply(quantity).intValue()+"";
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtResolvedDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSender1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRequestDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderItem = new javax.swing.JTable();
        btnOrder = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<< Back");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setText("ResolvedDate:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        txtResolvedDate.setEnabled(false);
        add(txtResolvedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 210, 30));

        jLabel2.setText("Sender:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        txtSender1.setEnabled(false);
        add(txtSender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 210, 30));

        jLabel3.setText("RequestDate:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtRequestDate.setEnabled(false);
        add(txtRequestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 210, 30));

        tblOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookName", "Quantity", "Per Price", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(tblOrderItem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 240, 530, 140));

        btnOrder.setText("Order");
        add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        container.remove(this);
        Component[] coms=container.getComponents();
        Component c=(Component)coms[coms.length-1];
        PB_workAreaJPanel jp=(PB_workAreaJPanel)c;
        jp.populate();
        CardLayout l=(CardLayout)container.getLayout();
        l.previous(container);
    }                                       

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PB_newRequestJPanel jp=new PB_newRequestJPanel(container,wr,user);
        CardLayout l=(CardLayout)container.getLayout();
        container.add(jp);
        l.next(container);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrderItem;
    private javax.swing.JTextField txtRequestDate;
    private javax.swing.JTextField txtResolvedDate;
    private javax.swing.JTextField txtSender1;
    // End of variables declaration//GEN-END:variables
}
