/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.SYS_ManageRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.BScustomerLogin.CustomerCreateJPanel;
import userinterface.BScustomerLogin.CustomerManageJPanel;
import userinterface.BookStoreManagement.BSManagerMngJPanel;
import userinterface.Enterprise_ManageRole.EnterpriseManageWorkAreaJPanel;
import userinterface.PT_ManageRole.PT_ManageRoleJPanel;
import userinterface.PT_PrintingMemberRole.PrintingMemberRoleJPanel;
import userinterface.SYS_ManageRole.SYSAdminWorkAreaJPanel;


/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public static EcoSystem system;
    public static DB4OUtil dB4OUtil = DB4OUtil.getInstance();



    public static UserAccountDirectory userAccountDirectory;
    
    public MainJFrame() {
        initComponents();
       
        system = dB4OUtil.retrieveSystem();          
        userAccountDirectory=system.getUserAccountDirectory();
        
        this.setSize(1200, 800);
      if(userAccountDirectory.getUserAccountList().isEmpty())
        insertU();
        initialID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSplitPane1.setDividerSize(0);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loginJButton.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        userNameJTextField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N

        passwordField.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("Password");

        logoutJButton.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Customer Rigister");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logoutJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(loginJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginJLabel)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(loginJLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginJButton)
                        .addGap(34, 34, 34)
                        .addComponent(logoutJButton)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initialID(){
        ArrayList<Network> ntlist=system.getNetworkDirectory().getNetworkList();
        int size=ntlist.size();
        int maxnt=0;
        if(ntlist.size()>=1){
       maxnt=ntlist.get(size-1).getNetworkID()+1;
       
        
        }
        Network.counter=maxnt+1;
         System.out.println("last network id is"+Network.counter);
        int maxen=0;
        int maxor=0;
        for(Network n:ntlist){
           ArrayList<Enterprise>  enlist=n.getEnterpriseDirectory().getEnterpriseList();
          
          if(enlist.size()>=1){
           if(enlist.get(enlist.size()-1).getEnterpriseID()>=maxen)
               maxen=enlist.get(enlist.size()-1).getEnterpriseID();
           for(Enterprise e:enlist){
               
            ArrayList<Organization>  orlist=e.getOrganizationDirectory().getOrganizationList();
            if(orlist.size()>=1){
            if(orlist.get(orlist.size()-1).getOrganizationID()>=maxor)
            maxor=orlist.get(orlist.size()-1).getOrganizationID();
            }
           }
          }
          
        
        }
         Enterprise.counter=maxen+1;
         Organization.counter=maxor+1;
         System.out.println("last Enterprise id is"+Enterprise.counter);
         System.out.println("last Organinization id is"+Organization.counter);
       
       
    
    }
    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name    
        String username=userNameJTextField.getText();
        String password=passwordField.getText();
       
        system = dB4OUtil.retrieveSystem();
    //    System.out.println("你输入的账号和密码是："+username+password);
        UserAccount useraccount=system.getUserAccountDirectory().authenticateUser(username, password);
        if(useraccount!=null){
            //获得useraccount里面存储的rolename=roletype，以此来判断是哪一种role在登陆
            String rolename=useraccount.getRole().getRolename();
        System.out.println("你输入的用户名对应的rolemname是："+rolename);
//Role Type包括：
//"BS_BookManageRole","BS_CustomerRole","BS_SecondHandManageRole"
//"Deli_DeliveryManRole","Deli_DeliveryManageRole"
//"PT_ManageRole","PT_PrintingMemberRole"
//"SYS_ManageRole"
//"PB_ManageRole"
//"Enterprise_ManageRole"
//__________________下面未完成 待续———————————————————— 
            if(rolename.equals("BS_BookManageRole"))
            {
                //AdminWorkAreaJPanel adminWorkAreaJPanel = new AdminWorkAreaJPanel(container,system.getRestaurantDirectory().RestaurantSearch(username));
               // container.add("adminWorkAreaJPanel", adminWorkAreaJPanel);
                BSManagerMngJPanel BSManageRole = new BSManagerMngJPanel(container,useraccount);
                container.add("BSManagerMngJPanel", BSManageRole);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
            else if(rolename.equals("BS_CustomerRole"))
            {
              //  CustomerChooseRes customerChooseRes = new CustomerChooseRes(container,system.getCustomerDirectory().CustomerSearch(username));
              //  container.add("CustomerChooseRes", customerChooseRes);
                CustomerManageJPanel customerRole = new CustomerManageJPanel(container,useraccount);
                container.add("CustomerManageJPanel", customerRole);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
            else if(rolename.equals("BS_SecondHandManageRole"))
            {
              //  CustomerChooseRes customerChooseRes = new CustomerChooseRes(container,system.getCustomerDirectory().CustomerSearch(username));
              //  container.add("CustomerChooseRes", customerChooseRes);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
            else if(rolename.equals("Deli_DeliveryManRole"))
            {
              //  CustomerChooseRes customerChooseRes = new CustomerChooseRes(container,system.getCustomerDirectory().CustomerSearch(username));
              //  container.add("CustomerChooseRes", customerChooseRes);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
            else if(rolename.equals("Deli_DeliveryManageRole"))
            {
              //  CustomerChooseRes customerChooseRes = new CustomerChooseRes(container,system.getCustomerDirectory().CustomerSearch(username));
              //  container.add("CustomerChooseRes", customerChooseRes);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
            else if(rolename.equals("PT_ManageRole"))
            {
                PrintingMemberRoleJPanel printingMemberRole = new PrintingMemberRoleJPanel();
                container.add("printingMemberRole", printingMemberRole);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
            else if(rolename.equals("PT_PrintingMemberRole"))
            {
                PrintingMemberRoleJPanel printingMemberRole = new PrintingMemberRoleJPanel();
                container.add("printingMemberRole", printingMemberRole);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
           else if(rolename.equals("PB_ManageRole"))
            {
                PT_ManageRoleJPanel pT_ManageRoleJPanel = new PT_ManageRoleJPanel();
                container.add("pT_ManageRoleJPanel", pT_ManageRoleJPanel);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
            }
            else if(rolename.equals("Enterprise_ManageRole"))
            {
                EnterpriseManageWorkAreaJPanel enterpriseManageWorkAreaJPanel = new EnterpriseManageWorkAreaJPanel(container,useraccount);
                container.add("enterpriseManageWorkAreaJPanel", enterpriseManageWorkAreaJPanel);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
                

            }
            else if(rolename.equals("SYS_ManageRole"))
            {               
               SYSAdminWorkAreaJPanel sYSAdminWorkAreaJPanel = new SYSAdminWorkAreaJPanel(container,system);
               container.add("sYSAdminWorkAreaJPanel", sYSAdminWorkAreaJPanel);
               CardLayout layout = (CardLayout) container.getLayout();
               layout.next(container);
            }
            
        }
        else
            JOptionPane.showMessageDialog(null, "Incorrect username or password !");
            
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
     //   logoutJButton.setEnabled(false);
    //    userNameJTextField.setEnabled(true);
   //     passwordField.setEnabled(true);
   //     loginJButton.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
       // dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CustomerCreateJPanel customerCreate = new CustomerCreateJPanel(container,system);
        container.add("CustomerCreateJPanel", customerCreate);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables

    private void insertU(){
           
        SYS_ManageRole sYS_ManageRole  =new SYS_ManageRole();
        system.getUserAccountDirectory().createUserAccount("SYS-user1", "123", sYS_ManageRole);
       
         dB4OUtil.storeSystem(system);
    }

}
