/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BScustomerLogin;

/**
 *
 * @author wangcong
 */
public class CustomerManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerManageJPanel
     */
    public CustomerManageJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuying = new javax.swing.JButton();
        btnSelling = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Welcome Customer!");

        btnBuying.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBuying.setText("Go to buy!");

        btnSelling.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSelling.setText("Go to sell!");

        btnOrderHistory.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnOrderHistory.setText("Order History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnOrderHistory))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuying)
                            .addComponent(btnSelling))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(btnBuying)
                .addGap(43, 43, 43)
                .addComponent(btnSelling)
                .addGap(46, 46, 46)
                .addComponent(btnOrderHistory)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuying;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnSelling;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
