/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BScustomerLogin;

import Business.Enterprise.BookstoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.OrderSystem.Book;
import Business.Organization.BS_BookManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import static userinterface.MainJFrame.log;
import static userinterface.MainJFrame.system;

/**
 *
 * @author wangcong
 */
public class CustomerManageJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount customer;
    /**
     * Creates new form CustomerManageJPanel
     */
    public CustomerManageJPanel(JPanel container, UserAccount customer) {
        initComponents();
        log.info("Login: Customer User:"+customer.getUsername());
        this.container = container;
        this.customer = customer;
        this.setBackground(new Color(253,251,239));
       // JTableHeader head = tblBookStore.getTableHeader(); // 创建表格标题对象
      //  head.setPreferredSize(new Dimension(head.getWidth(), 24));// 设置表头大小
      //  head.setFont(new Font("Times New Roman", Font.PLAIN, 24));// 设置表格字体
      //  populateTable();
    }
    
    public void populateTable(){
        List<Network> networkList = new ArrayList<>();
        networkList = system.getNetworkDirectory().getNetworkList();
        List<Book> sBookList = new ArrayList<>();

       // DefaultTableModel model=(DefaultTableModel)tblBookStore.getModel();
      //  model.setRowCount(0);

        for (Network network : networkList){
            List<Enterprise> enterpriseList = new ArrayList<>();
            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            for(Enterprise enterprise : enterpriseList){
                if(enterprise.getEnterpriseType().equals("Type-BookStore")){
                    BookstoreEnterprise bookstore = (BookstoreEnterprise)enterprise;
                    ArrayList<Organization> organizations = bookstore.getOrganizationDirectory().getOrganizationList();
                    for (Organization organization : organizations) {
                        if (organization instanceof BS_BookManagementOrganization) {
                            BS_BookManagementOrganization bso = (BS_BookManagementOrganization) organization;
                            sBookList= bso.getBookDirectory().getBooklist();
                            for(Book book : sBookList){
                                    Object row[]=new Object[6];
                                    row[0]= book;
                                    row[1] = network;
                                    row[2] = bookstore;
                                    row[3]= String.valueOf(book.getPrice());
                                    row[4]= book.getStatus();
                                    row[5] = book.getTotalQuantity();
                                //    model.addRow(row);
                                }}
                            }
                        }
                    }
                }
    }
    
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        //populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuying = new javax.swing.JButton();
        btnSelling = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 251, 239));
        setPreferredSize(new java.awt.Dimension(950, 800));
        setRequestFocusEnabled(false);

        btnBuying.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        btnBuying.setText("Go to buy!");
        btnBuying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyingActionPerformed(evt);
            }
        });

        btnSelling.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        btnSelling.setText("Go to sell!");
        btnSelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellingActionPerformed(evt);
            }
        });

        btnOrderHistory.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        btnOrderHistory.setText("Order History");
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 3, 48)); // NOI18N
        jLabel6.setText("Welcome to Online Bookstore !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelling)
                            .addComponent(btnBuying)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnOrderHistory)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnBuying)
                .addGap(105, 105, 105)
                .addComponent(btnSelling)
                .addGap(94, 94, 94)
                .addComponent(btnOrderHistory)
                .addGap(227, 227, 227))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyingActionPerformed

        CustomerBuyingJPanel customerBuying = new CustomerBuyingJPanel(container, customer);
        container.add("CustomerBuyingJPanel", customerBuying);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnBuyingActionPerformed

    private void btnSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellingActionPerformed
        
        CustomerSellingJPanel customerSelling = new CustomerSellingJPanel(container,customer);
        container.add("CustomerSellingJPanel", customerSelling);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnSellingActionPerformed

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        
        OrderHistoryJPanel orderHistory = new OrderHistoryJPanel(container,customer);
        container.add("OrderHistoryJPanel", orderHistory);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnOrderHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuying;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnSelling;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
