/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BScustomerLogin;

import Business.Enterprise.BookstoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.OrderSystem.Book;
import Business.OrderSystem.Order;
import Business.OrderSystem.OrderItem;
import Business.Organization.BS_BookManagementOrganization;
import Business.Organization.BS_SecondHandOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userinterface.MainJFrame.dB4OUtil;
import static userinterface.MainJFrame.system;

/**
 *
 * @author wangcong
 */
public class CustomerSellingJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount customer;
    /**
     * Creates new form CustomerSellingJPanel
     */
    public CustomerSellingJPanel(JPanel container,UserAccount customer) {
        this.setBackground(new Color(253,251,239));
        this.container = container;
        this.customer = customer;
        initComponents();
        txtCustomerAddress.setText(customer.getAddress());
        populateCombo();
        
    }
public static boolean isNumeric(String str){

        String reg = "^[0-9]+(.[0-9]+)?$";

        return str.matches(reg);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBookStore = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtExpectedPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setBackground(new java.awt.Color(253, 251, 239));
        setPreferredSize(new java.awt.Dimension(950, 800));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 3, 48)); // NOI18N
        jLabel1.setText("Selling Your Book");

        btnBack.setFont(new java.awt.Font("Tekton Pro Ext", 1, 30)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnOrder.setFont(new java.awt.Font("Tekton Pro Ext", 1, 30)); // NOI18N
        btnOrder.setText("Commit");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setText("Select your location:");

        comboNetwork.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        comboNetwork.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNetworkItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setText("Select your wanted bookstore:");

        comboBookStore.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Number of Second-hand book:");

        txtNumber.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel6.setText("Customer Address:");

        txtCustomerAddress.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setText("Expected Price:");

        txtExpectedPrice.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel8.setText("Extra Information:");

        txtComment.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txtComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel10.setText("Book Name:");

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 56, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(510, 510, 510)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtExpectedPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCustomerAddress)
                            .addComponent(txtNumber)
                            .addComponent(txtComment)
                            .addComponent(comboNetwork, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBookStore, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBookStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtExpectedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnOrder))
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);        
        CardLayout layout=(CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    public void populateCombo() {
        //populate the location option
        comboNetwork.removeAllItems();
        for (Network nt : system.getNetworkDirectory().getNetworkList()) {
            comboNetwork.addItem(nt);
        }

        //populate all boosktores
        comboBookStore.removeAllItems();
        Network network = (Network) comboNetwork.getSelectedItem();
        for (Enterprise en : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (en.getEnterpriseType().equals("Type-BookStore")) {
                comboBookStore.addItem((BookstoreEnterprise) en);
            }
        }
    }
    
    private void comboNetworkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNetworkItemStateChanged
        //make two comboBox related
        comboBookStore.removeAllItems();
        Network network = (Network) comboNetwork.getSelectedItem();
        if (network == null) {
            return;
        }
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().equals("Type-BookStore")) {
                comboBookStore.addItem((BookstoreEnterprise) enterprise);
            }
        }
    }//GEN-LAST:event_comboNetworkItemStateChanged

    private void txtCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentActionPerformed

    }//GEN-LAST:event_txtCommentActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        
         String str=txtNumber.getText();
          String str1=txtExpectedPrice.getText();
        if(!isNumeric(str)||!isNumeric(str1)){
              JOptionPane.showMessageDialog(null, "Please input a valid number!", "Warning", JOptionPane.WARNING_MESSAGE);
          
        }
        else if(txtName.getText().equals("")||txtExpectedPrice.getText().equals("")||txtNumber.getText().equals("")||txtCustomerAddress.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Please fill the infomation!", "Warning", JOptionPane.WARNING_MESSAGE);
          
        }
        else{
        
        
        Network network = (Network)comboNetwork.getSelectedItem();
        BookstoreEnterprise bookstore = (BookstoreEnterprise)comboBookStore.getSelectedItem();
        int number = Integer.parseInt(txtNumber.getText());
        
        String expectedPrice = txtExpectedPrice.getText();
        String FinalPrice = null;
        String extraInfo = txtComment.getText();
        
        /*new order*/
        Order order = new Order();
        order.setSellBookName(txtName.getText());
        order.setUserAccount(customer);
        order.setExpectedPrice(expectedPrice);
        order.setFinalPrice(FinalPrice);
        order.setSellingNumber(number);
        order.setStatus("Waiting Bookstore Process");
        /*方便user更改地址*/
        order.setAddress(txtCustomerAddress.getText());
        order.setComments(extraInfo);
        
        /*new workRequest to customer*/
        customer.getUserorderlist().add(order);
        WorkRequest workRequest = new WorkRequest();
        workRequest.setOrder(order);
        workRequest.setSenderUserAccount(customer);
        workRequest.setReceiverEnterprise(bookstore);
        workRequest.setStatus("Uncompleted");
        workRequest.setMessage(txtComment.getText());
        customer.getWorkQueue().addNewCusToSHBSRequest(workRequest);
        
        
        /*add the workrequest to the BS_SecondHandOrganization*/
        ArrayList<Organization> bookManageList = bookstore.getOrganizationDirectory().getOrganizationList();
        if(bookManageList == null){
            JOptionPane.showMessageDialog(null,"The book does not have second-hand service!");
            return;
        }
        BS_SecondHandOrganization bookstoreOrg=null;
        for (Organization org : bookManageList) {
            if (org.getOrgtypename().equals("BS_SecondHandOrganization")) {
                bookstoreOrg = (BS_SecondHandOrganization) org;
                bookstoreOrg.getWorkQueue().addNewCusToSHBSRequest(workRequest);
                JOptionPane.showMessageDialog(null, "The Order Has been sent to the bookstore. The bookstore will reply you in 7 days");
                dB4OUtil.storeSystem(system); 
                txtName.setEnabled(false);
                 txtNumber.setEnabled(false);
                  txtComment.setEnabled(false);
                   txtCustomerAddress.setEnabled(false);
                    txtExpectedPrice.setEnabled(false);
                    btnOrder.setEnabled(false);
            }
        }
        if(bookstoreOrg==null){
            JOptionPane.showMessageDialog(null,"The book does not have second-hand service!");
        }
     } 
        
    }//GEN-LAST:event_btnOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOrder;
    private javax.swing.JComboBox<BookstoreEnterprise> comboBookStore;
    private javax.swing.JComboBox<Network> comboNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtExpectedPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
