/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BScustomerLogin;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author wangcong
 */
public class OrderHistoryJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount customer;
    /**
     * Creates new form OrderHistoryJPanel
     */
    public OrderHistoryJPanel(JPanel container,UserAccount customer) {
        this.container = container;
        this.customer = customer;
        initComponents();
        this.setBackground(new Color(253,251,239));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnBuyingOrder = new javax.swing.JButton();
        btnSellingOrder = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 251, 239));
        setPreferredSize(new java.awt.Dimension(950, 800));

        btnBack.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnBuyingOrder.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnBuyingOrder.setText("Buying Orders");
        btnBuyingOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyingOrderActionPerformed(evt);
            }
        });

        btnSellingOrder.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnSellingOrder.setText("Selling Orders");
        btnSellingOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellingOrderActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 3, 48)); // NOI18N
        jLabel6.setText("View Your Orders");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel6)
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSellingOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuyingOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(btnBuyingOrder)
                .addGap(116, 116, 116)
                .addComponent(btnSellingOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBuyingOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyingOrderActionPerformed
        OrderBookHistoryJPanel orderBookHistoryJPanel = new OrderBookHistoryJPanel(container,customer);
        container.add("OrderBookHistoryJPanel", orderBookHistoryJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnBuyingOrderActionPerformed

    private void btnSellingOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellingOrderActionPerformed
        OrderSellingHistoryJPanel orderSellingHistoryJPanel = new OrderSellingHistoryJPanel(container,customer);
        container.add("OrderSellingHistoryJPanel", orderSellingHistoryJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnSellingOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuyingOrder;
    private javax.swing.JButton btnSellingOrder;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
