/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BookStoreManagement;

/**
 *
 * @author wangcong
 */
public class BSManagerMngJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BSManagerMngJPanel
     */
    public BSManagerMngJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewOrders = new javax.swing.JButton();
        btnUploadBook = new javax.swing.JButton();
        btnUploadBook1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Welcome! Book Store Manager");

        btnViewOrders.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnViewOrders.setText("Manage Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnUploadBook.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnUploadBook.setText("Manage Books");
        btnUploadBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadBookActionPerformed(evt);
            }
        });

        btnUploadBook1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnUploadBook1.setText("Manage Bookstore Staff");
        btnUploadBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadBook1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUploadBook)
                    .addComponent(btnViewOrders))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUploadBook1)
                    .addComponent(jLabel1))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btnViewOrders)
                .addGap(36, 36, 36)
                .addComponent(btnUploadBook)
                .addGap(40, 40, 40)
                .addComponent(btnUploadBook1)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadBookActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnUploadBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadBook1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUploadBook;
    private javax.swing.JButton btnUploadBook1;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
