/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PT_ManageRole;

import userinterface.Deli_ManagerRole.*;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author liu
 */
public class PTManage_workAreaJPanel extends javax.swing.JPanel {

    JPanel container;
    UserAccount ua;
    //WorkRequest wr;
    public PTManage_workAreaJPanel( JPanel container,UserAccount ua) {
        initComponents();
        this.container=container;
        this.ua=ua;
        labelUser.setText(ua.getUsername());
        labelRole.setText(ua.getEmployee().getEnterprise().getEnterpriseName()+" "+ua.getEmployee().getOrganization().getOrgtypename());
        
        JTableHeader head = tblQueue.getTableHeader(); // 创建表格标题对象
        head.setPreferredSize(new Dimension(head.getWidth(), 36));// 设置表头大小
        head.setFont(new Font("Times New Romans", Font.PLAIN, 36));// 设置表格字体
        populate();
        comboDeliveryman.removeAll();
        
        for(Organization o:ua.getEmployee().getEnterprise().getOrganizationDirectory().getOrganizationList()){
            if(o.getOrgtypename().equals("Deli_DeliveryManOrganization")){
                for(UserAccount u:o.getUserAccountDirectory().getUserAccountList()){
                    comboDeliveryman.addItem(u.toString());
                }
            } 
        }
    }
    
    public void populate(){
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:ua.getWorkQueue().getWorkRequestList()){
            if(wr.getStatus().equals(("Uncompleted"))){
                Object[] row=new Object[6];
                row[0]=wr;
                if(wr.getSenderEnterprise()!=null){
                    row[1]=wr.getSenderEnterprise().getEnterpriseName();              
                }else{
                    row[1]=wr.getSenderUserAccount().getUsername();
                }
                if(wr.getReceiverEnterprise()!=null){
                    row[2]=wr.getReceiverEnterprise().getEnterpriseName();
                }else{
                    row[2]=wr.getReceiverUserAccount().getUsername();
                }
                row[3]=wr.getStatus();
                row[4]=wr.getMessage();
                row[5]=wr.getResolveDate().toString();
                dtm.addRow(row);   
            }           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        btnUnfinished = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQueue = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboDeliveryman = new javax.swing.JComboBox<>();
        btnCommit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSenderAddr = new javax.swing.JTextField();
        txtSenderPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtReceiver = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtReceiverAddr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtReceiverPhone = new javax.swing.JTextField();
        labelRole = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(950, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Welcome! ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelUser.setText("labelUser");
        add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 20));

        btnUnfinished.setText("Unfinished");
        add(btnUnfinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btnAll.setText("All");
        add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        tblQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestDate", "Sender", "Receiver", "Status", "Message", "ResolveDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQueue);
        if (tblQueue.getColumnModel().getColumnCount() > 0) {
            tblQueue.getColumnModel().getColumn(0).setResizable(false);
            tblQueue.getColumnModel().getColumn(1).setResizable(false);
            tblQueue.getColumnModel().getColumn(2).setResizable(false);
            tblQueue.getColumnModel().getColumn(3).setResizable(false);
            tblQueue.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 920, 290));

        btnDetails.setText("Detials");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 150, 40));

        jLabel8.setText("Choose a delivery man:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 770, -1, -1));

        comboDeliveryman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeliverymanActionPerformed(evt);
            }
        });
        add(comboDeliveryman, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 780, -1, -1));

        btnCommit.setText("Commit");
        btnCommit.setActionCommand("");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        add(btnCommit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 760, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Sender:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtSender.setEnabled(false);
        jPanel1.add(txtSender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, 30));

        jLabel7.setText("Address:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtSenderAddr.setEnabled(false);
        jPanel1.add(txtSenderAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 200, 30));

        txtSenderPhone.setEnabled(false);
        jPanel1.add(txtSenderPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 30));

        jLabel3.setText("Phone:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTabbedPane1.addTab("Sender", jPanel1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 340, 220));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Receiver:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtReceiver.setEnabled(false);
        jPanel2.add(txtReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 200, 30));

        jLabel6.setText("Address:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtReceiverAddr.setEnabled(false);
        jPanel2.add(txtReceiverAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 200, 30));

        jLabel5.setText("Phone:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txtReceiverPhone.setEnabled(false);
        jPanel2.add(txtReceiverPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 200, 30));

        jTabbedPane2.addTab("Receiver", jPanel2);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 350, 220));

        labelRole.setText("jLabel2");
        add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 170, 20));

        jLabel9.setText("Work Area");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int selected=tblQueue.getSelectedRow();
        if(selected<0){
            JOptionPane.showMessageDialog(null, "Please select a work request", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            WorkRequest wr=(WorkRequest)tblQueue.getValueAt(selected, 0);   
            if(wr.getSenderEnterprise()!=null){
                txtSender.setText(wr.getSenderEnterprise().getEnterpriseName());
                txtSenderAddr.setText(wr.getSenderEnterprise().getAddress());
                txtSenderPhone.setText(wr.getSenderEnterprise().getPhone());
            }else{
                txtSender.setText(wr.getSenderUserAccount().getUsername());
                txtSenderAddr.setText(wr.getSenderUserAccount().getAddress());
                txtSenderPhone.setText(wr.getSenderUserAccount().getPhone());
            }
            if(wr.getReceiverEnterprise()!=null){
                txtReceiver.setText(wr.getReceiverEnterprise().getEnterpriseName());
                txtReceiverAddr.setText(wr.getReceiverEnterprise().getAddress());
                txtReceiverPhone.setText(wr.getReceiverEnterprise().getPhone());
            }else{
                txtReceiver.setText(wr.getReceiverUserAccount().getUsername());
                txtReceiverAddr.setText(wr.getReceiverUserAccount().getAddress());
                txtReceiverPhone.setText(wr.getReceiverUserAccount().getPhone());
            }          
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        int selected=tblQueue.getSelectedRow();
        WorkRequest wr=(WorkRequest)tblQueue.getValueAt(selected, 0);      
        WorkRequest newWR=new WorkRequest();
        newWR.setSenderUserAccount(ua);
        UserAccount deliMan=(UserAccount)comboDeliveryman.getSelectedItem();               
        newWR.setOrder(wr.getOrder());
        newWR.setStatus("Uncompleted");
        newWR.setRequestDate(new Date());
        for(UserAccount u:ua.getEmployee().getOrganization().getUserAccountDirectory().getUserAccountList()){
            if(u.equals(deliMan)){
                newWR.setReceiverUserAccount(u);
                u.getWorkQueue().addNewRequest(newWR);
            }
        }

        int check=JOptionPane.YES_NO_OPTION;
        String mesg = JOptionPane.showInputDialog(null,"Message: \n","Mesg",check);
        if(check==JOptionPane.YES_OPTION){
            newWR.setMessage(mesg);
            JOptionPane.showMessageDialog(null, "A new work request has been sent out successfully.");
            wr.setStatus("Completed");
        }
        populate();
    }//GEN-LAST:event_btnCommitActionPerformed

    private void comboDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeliverymanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDeliverymanActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {                                       
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:ua.getWorkQueue().getWorkRequestList()){           
            Object[] row=new Object[6];
            row[0]=wr;
            if(wr.getSenderEnterprise()!=null){
                row[1]=wr.getSenderEnterprise().getEnterpriseName();              
            }else{
                row[1]=wr.getSenderUserAccount().getUsername();
            }
            if(wr.getReceiverEnterprise()!=null){
                row[2]=wr.getReceiverEnterprise().getEnterpriseName();
            }else{
                row[2]=wr.getReceiverUserAccount().getUsername();
            }
            row[3]=wr.getStatus();
            row[4]=wr.getMessage();
            row[5]=wr.getResolveDate().toString();
            dtm.addRow(row);                         
        }
    }                                      

    private void btnUnfinishedActionPerformed(java.awt.event.ActionEvent evt) {                                              
        populate();
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnUnfinished;
    private javax.swing.JComboBox<String> comboDeliveryman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTable tblQueue;
    private javax.swing.JTextField txtReceiver;
    private javax.swing.JTextField txtReceiverAddr;
    private javax.swing.JTextField txtReceiverPhone;
    private javax.swing.JTextField txtSender;
    private javax.swing.JTextField txtSenderAddr;
    private javax.swing.JTextField txtSenderPhone;
    // End of variables declaration//GEN-END:variables
}
