/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SYS_ManageRole;


import Business.Employee.Employee;
import Business.Role.BS_CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userinterface.MainJFrame.dB4OUtil;
import static userinterface.MainJFrame.system;

/**
 *
 * @author AEDSpring2019
 */
public class AddNewCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AdminScreen
     */
    
    private JPanel userProcessContainer;
    
    public AddNewCustomer(JPanel userProcessContainer) {
        initComponents();
        this. userProcessContainer =  userProcessContainer;
        this.setBackground(new Color(253,251,239));
    }
    private boolean checkusername(){
        Pattern p=Pattern.compile("^[a-zA-Z0-9]{6,}$");
        Matcher m=p.matcher(txtUser.getText());
        boolean b=m.matches();
        System.out.println(b+"name");
        return b;
    
    }
    private boolean checkpassword(){//>=6 >=1 upper case letter >=1 lower case letter one digit .
        

        Pattern p0=Pattern.compile("^(?![a-z0-9]+$)(?![A-Za-z]+$)(?![A-Z0-9]+$)[a-zA-Z0-9]{6,}$");
        Matcher m0=p0.matcher(txtPword.getText());
        boolean b0=m0.matches();
        System.out.println(b0);
         if(!b0){
              jLabel2.setForeground(Color.red);
              JOptionPane.showMessageDialog(null,"The password format is incorrect!","warning",JOptionPane.WARNING_MESSAGE);
            
            return false;
        }
       
       
        return true;
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCreate = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPword = new javax.swing.JTextField();
        txtRePword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(253, 251, 239));
        setPreferredSize(new java.awt.Dimension(950, 800));

        btnCreate.setFont(new java.awt.Font("Tekton Pro Ext", 1, 30)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N

        txtPword.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N

        txtRePword.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel3.setText(" Re-enter Password:");

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 3, 42)); // NOI18N
        jLabel6.setText("Please Register Your New Account");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("At least 6 characters and must contain uppercase, lowercase, number");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setText("At least 6 characters and can contain letters and numbers");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel8.setText("Address:");

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel9.setText("Telephone Number:");

        t1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel7))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel9))
                                        .addGap(3, 3, 3))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtRePword, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(t1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel6))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRePword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnCreate)
                .addGap(125, 125, 125)
                .addComponent(jLabel4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(txtRePword.getText().equals("")||txtPword.getText().equals("")||txtUser.getText().equals("")||txtAddress.getText().equals("")||t1.getText().equals("")){
               JOptionPane.showMessageDialog(null,"Please fill all the information !","warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(!(txtRePword.getText().equals(txtPword.getText()))){
            jLabel2.setForeground(Color.red);
            jLabel3.setForeground(Color.red);
            
        
                JOptionPane.showMessageDialog(null,"The two passwords are different !","warning",JOptionPane.WARNING_MESSAGE);
            
        }
        else if( !checkusername()){
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
            
             jLabel1.setForeground(Color.red);
             JOptionPane.showMessageDialog(null,"The username format is incorrect","warning",JOptionPane.WARNING_MESSAGE);
             
        
        }
        else if(!checkpassword()){
           jLabel1.setForeground(Color.black); jLabel3.setForeground(Color.black);
           jLabel2.setForeground(Color.red);
        }
        else if(!(system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUser.getText()))){
             JOptionPane.showMessageDialog(null,"The username already exists","warning",JOptionPane.WARNING_MESSAGE);
             
            jLabel1.setForeground(Color.red);
            jLabel3.setForeground(Color.black);
            jLabel2.setForeground(Color.black);
        }
        else{
            jLabel1.setForeground(Color.black);
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
        
        BS_CustomerRole bS_CustomerRole  =new BS_CustomerRole();
        Employee emplo=new Employee();
        UserAccount ua=system.getUserAccountDirectory().createUserAccount(txtUser.getText(), txtPword.getText(), emplo,bS_CustomerRole,txtAddress.getText());
       ua.setPhone(t1.getText());
        JOptionPane.showMessageDialog(null, "Create Useraccount Successfully!", "Successfully", JOptionPane.INFORMATION_MESSAGE);
        dB4OUtil.storeSystem(system);
        txtUser.setText("");
        txtPword.setText("");
        txtRePword.setText("");
        txtAddress.setText("");
        t1.setText("");
        
        }


        
    }//GEN-LAST:event_btnCreateActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtPword;
    private javax.swing.JTextField txtRePword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
