/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BSbusiness;

import Business.OrderSystem.OrderItem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.LayoutManager;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author liu
 */
public class SellingBooksRatio extends javax.swing.JPanel {

    JPanel container;
    UserAccount ua;
    public SellingBooksRatio(JPanel container,UserAccount ua) {
        initComponents();
        this.setBackground(new Color(253,251,239));
        this.container=container;
        this.ua=ua;
        populateChart();
    }
    
    public void populateChart(){
        JFreeChart chart=ChartFactory.createBarChart("Books Sales Condition","Book","Sales",getData());
        CategoryPlot plot=chart.getCategoryPlot();
        CategoryAxis domainAxis=plot.getDomainAxis();
        domainAxis.setLabelFont(new Font("Times New Roman",Font.PLAIN,24));
        domainAxis.setTickLabelFont(new Font("Times New Roman",Font.PLAIN,24));
        ValueAxis rangeAxis=plot.getRangeAxis();
        rangeAxis.setLabelFont(new Font("Times New Roman",Font.PLAIN,24));
        chart.getLegend().setItemFont(new Font("Times New Roman",Font.PLAIN,24));
        chart.getTitle().setFont(new Font("Times New Roman",Font.PLAIN,24));
        ChartPanel jp=new ChartPanel(chart,true);
        jp.setBounds(100, 100, 700, 600);
        this.add(jp);
    }
    
    public CategoryDataset getData(){
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        List<WorkRequest> workQueue=null;
        for(Organization o:ua.getEmployee().getEnterprise().getOrganizationDirectory().getOrganizationList()){
            if(o.getOrgtypename().equals("BS_BookManagementOrganization")){
                workQueue=o.getWorkQueue().getWorkRequestList();
            }
        }
        if(workQueue!=null){
            Map<String,Integer> map=new HashMap<>();
            for(WorkRequest w:workQueue){
                for(OrderItem o:w.getOrder().getOrderItems()){
                    map.put(o.getBookname(),!map.containsKey(o.getBookname())?o.getQuantity():map.get(o.getBookname())+o.getQuantity());
                }
            }
//            for(OrderItem o:map.keySet()){
//                System.out.print(o.getBookname()+map.get(o));
//            }
            List<Map.Entry<String,Integer>> l=new ArrayList<>();
            l.addAll(map.entrySet());
            Collections.sort(l, new Comparator<Map.Entry<String,Integer>>(){
                @Override
                public int compare(Map.Entry<String,Integer> m1,Map.Entry<String,Integer> m2){
                    return m2.getValue()-m1.getValue();
                }
            });           
            for(int i=0;i<l.size();i++){
                dataset.addValue(l.get(i).getValue(), "bs1", l.get(i).getKey());  
            }                        
        }         
        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(253, 251, 239));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 3, 36)); // NOI18N
        jLabel1.setText("Books Selling Condition");

        btnBack.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBack)
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addContainerGap(738, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this); 
        CardLayout l=(CardLayout)container.getLayout();
        l.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
