/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Deli_ManRole;

import Business.EcoSystem;
import Business.OrderSystem.OrderItem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import userinterface.MainJFrame;
import static userinterface.MainJFrame.dB4OUtil;
import static userinterface.MainJFrame.system;
import zOthers.changeDate;
import zOthers.playMusic;
import static userinterface.MainJFrame.log;

/**
 *
 * @author liu
 */
public class DeliMan_workAreaJpanel extends javax.swing.JPanel {

    JPanel container;
    UserAccount ua;
    public DeliMan_workAreaJpanel(JPanel container,UserAccount user) {
        initComponents(); 
        log.info("Login: DeliveryMan User:"+user.getUsername());
        this.setBackground(new Color(253,251,239));
        this.container=container;
        this.ua=user;
        labelUser.setText("Enterprise: "+ua.getEmployee().getEnterprise().getEnterpriseName()+"("+ua.getEmployee().getEnterprise().getNetwork().getName()+")");   
        //labelRole.setText(ua.getEmployee().getEnterprise().getEnterpriseName()+" "+ua.getEmployee().getOrganization().getOrgtypename());      
        JTableHeader head = tblQueue.getTableHeader(); // 创建表格标题对象
        head.setPreferredSize(new Dimension(head.getWidth(), 24));// 设置表头大小
        head.setFont(new Font("Times New Roman", Font.PLAIN, 24));// 设置表格字体
        populate();
    }

    public void populate(){
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:ua.getWorkQueue().getWorkRequestList()){
            if(wr.getStatus().equals(("Uncompleted"))){
                Object[] row=new Object[7];
                row[0]=new changeDate().change(wr.getRequestDate());
                if(wr.getSenderEnterprise()!=null){
                    row[1]=wr.getSenderEnterprise().getEnterpriseName();              
                }else{
                    row[1]=wr.getSenderUserAccount().getUsername();
                }
                if(wr.getReceiverEnterprise()!=null){
                    row[2]=wr.getReceiverEnterprise().getEnterpriseName();
                }else{
                    row[2]=wr.getReceiverUserAccount().getUsername();
                }
                row[3]=wr.getStatus();
                row[4]=wr.getMessage();               
                row[5]=wr.getResolveDate()==null?"":new changeDate().change(wr.getResolveDate());              
                row[6]=wr;
                dtm.addRow(row);   
            }           
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUser = new javax.swing.JLabel();
        btnUnfinished = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQueue = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();
        btnArrival = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSenderAddr = new javax.swing.JTextField();
        txtSenderPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtReceiver = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtReceiverAddr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtReceiverPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 251, 239));
        setPreferredSize(new java.awt.Dimension(950, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUser.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUser.setText("labelUser");
        add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 350, 30));

        btnUnfinished.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        btnUnfinished.setText("Unfinished");
        btnUnfinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnfinishedActionPerformed(evt);
            }
        });
        add(btnUnfinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnAll.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        btnAll.setText("Finished");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        tblQueue.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestDate", "Sender", "Receiver", "Status", "Message", "ResolveDate", "Order ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQueue.setRowHeight(25);
        jScrollPane1.setViewportView(tblQueue);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 890, 210));

        btnDetails.setFont(new java.awt.Font("Tekton Pro Ext", 1, 26)); // NOI18N
        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, -1, -1));

        btnArrival.setFont(new java.awt.Font("Tekton Pro Ext", 1, 26)); // NOI18N
        btnArrival.setText("Arrival");
        btnArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrivalActionPerformed(evt);
            }
        });
        add(btnArrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 690, 140, -1));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Sender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtSender.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtSender.setEnabled(false);
        jPanel1.add(txtSender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 170, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Address:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 88, -1, 30));

        txtSenderAddr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtSenderAddr.setEnabled(false);
        txtSenderAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenderAddrActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenderAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 40));

        txtSenderPhone.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtSenderPhone.setEnabled(false);
        txtSenderPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenderPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenderPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Phone:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jTabbedPane1.addTab("Sender", jPanel1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 330, 240));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(300, 180));

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 180));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Receiver:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtReceiver.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtReceiver.setEnabled(false);
        jPanel2.add(txtReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 170, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Address:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtReceiverAddr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtReceiverAddr.setEnabled(false);
        txtReceiverAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceiverAddrActionPerformed(evt);
            }
        });
        jPanel2.add(txtReceiverAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Phone:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtReceiverPhone.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtReceiverPhone.setEnabled(false);
        txtReceiverPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceiverPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(txtReceiverPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, 40));

        jTabbedPane2.addTab("Receiver", jPanel2);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 340, 240));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 3, 36)); // NOI18N
        jLabel2.setText("Welcome! Delivery Man!");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrivalActionPerformed
        int selected=tblQueue.getSelectedRow();
        WorkRequest wr=(WorkRequest)tblQueue.getValueAt(selected, 6); 
        int dialogBtn=JOptionPane.YES_NO_OPTION;
        int dialogRes=JOptionPane.showConfirmDialog(null, "Are you sure to arrivel?","Warning",dialogBtn);
        if(dialogRes==JOptionPane.YES_OPTION){
            try {
                new playMusic().play("src/zOthers/ding.wav");
            } catch (IOException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            wr.setStatus("Completed");
            wr.setResolveDate(new Date());
            //快递员送书到顾客改order状态,快递员送书到书店改order状态
            wr.getOrder().setStatus("Arrival");
            JOptionPane.showMessageDialog(null, "Completed mission successfully");      
            populate();
            dB4OUtil.storeSystem(system);
        } 
    }//GEN-LAST:event_btnArrivalActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int selected=tblQueue.getSelectedRow();
        if(selected<0){
            JOptionPane.showMessageDialog(null, "Please select a work request", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            WorkRequest wr=(WorkRequest)tblQueue.getValueAt(selected, 6);   
            //确定取货地址和送达地址
            
            /*顾客买书：从书店送到顾客
            sender:bs receiver:deli
            起地：bs 终点：cus
            */
            if(wr.getSenderEnterprise().getEnterpriseType().equals("Type-BookStore")){
                if(wr.getMark()==0){
                    txtSender.setText(wr.getSenderEnterprise().getEnterpriseName());
                    txtSenderAddr.setText(wr.getSenderEnterprise().getAddress());
                    txtSenderPhone.setText(wr.getSenderEnterprise().getPhone());
                    txtReceiver.setText(wr.getOrder().getUserAccount().getUsername());
                    txtReceiverAddr.setText(wr.getOrder().getUserAccount().getAddress());
                    txtReceiverPhone.setText(wr.getOrder().getUserAccount().getPhone());
                }else{
                     /*顾客卖书：从顾客送到书店
                    顾客创造order
                    sender:bs receiver:deli
                    起点：cus 终点：bs
                    */
                    txtSender.setText(wr.getOrder().getUserAccount().getUsername());
                    txtSenderAddr.setText(wr.getOrder().getUserAccount().getAddress());
                    txtSenderPhone.setText(wr.getOrder().getUserAccount().getPhone());
                    txtReceiver.setText(wr.getSenderEnterprise().getEnterpriseName());
                    txtReceiverAddr.setText(wr.getSenderEnterprise().getAddress());
                    txtReceiverPhone.setText(wr.getSenderEnterprise().getPhone());
                }
            }
            
            /*从印刷厂送到书店
            sender:pt receiver:deli
            起点：pt 终点：bs
            */
            if(wr.getSenderEnterprise().getEnterpriseType().equals("Type-Printer")){
                txtSender.setText(wr.getSenderEnterprise().getEnterpriseName());
                txtSenderAddr.setText(wr.getSenderEnterprise().getAddress());
                txtSenderPhone.setText(wr.getSenderEnterprise().getPhone());
                txtReceiver.setText(wr.getOrder().getUserAccount().getEmployee().getEnterprise().getEnterpriseName());
                txtReceiverAddr.setText(wr.getOrder().getUserAccount().getEmployee().getEnterprise().getAddress());
                txtReceiverPhone.setText(wr.getOrder().getUserAccount().getEmployee().getEnterprise().getPhone());
            }         
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        
        
        for(WorkRequest wr:ua.getWorkQueue().getWorkRequestList()){    
               if(wr.getStatus().equals(("Completed"))){
            Object[] row=new Object[7];
            row[0]=new changeDate().change(wr.getRequestDate());
            if(wr.getSenderEnterprise()!=null){
                row[1]=wr.getSenderEnterprise().getEnterpriseName();              
            }else{
                row[1]=wr.getSenderUserAccount().getUsername();
            }
            if(wr.getReceiverEnterprise()!=null){
                row[2]=wr.getReceiverEnterprise().getEnterpriseName();
            }else{
                row[2]=wr.getReceiverUserAccount().getUsername();
            }
            row[3]=wr.getStatus();
            row[4]=wr.getMessage();
            row[5]=wr.getResolveDate()==null?"":new changeDate().change(wr.getResolveDate());              
            row[6]=wr;
            dtm.addRow(row);   
        }    }              
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnUnfinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnfinishedActionPerformed
        populate();
    }//GEN-LAST:event_btnUnfinishedActionPerformed

    private void txtSenderAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenderAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenderAddrActionPerformed

    private void txtReceiverAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceiverAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceiverAddrActionPerformed

    private void txtReceiverPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceiverPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceiverPhoneActionPerformed

    private void txtSenderPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenderPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenderPhoneActionPerformed
                                         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnArrival;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnUnfinished;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTable tblQueue;
    private javax.swing.JTextField txtReceiver;
    private javax.swing.JTextField txtReceiverAddr;
    private javax.swing.JTextField txtReceiverPhone;
    private javax.swing.JTextField txtSender;
    private javax.swing.JTextField txtSenderAddr;
    private javax.swing.JTextField txtSenderPhone;
    // End of variables declaration//GEN-END:variables
}
